name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10                  # Cambiado de 3.11 a 3.10 para compatibilidad total
  - pip<=25.1.1
  - pip
  - pandas>=1.5.0
  - numpy<=1.26.4               # Limitado para ser compatible con numba
  - matplotlib
  - pip:
      - mlflow==3.1.1
      - scikit-learn==1.3.2
      - ydata-profiling==4.6.5  # compatible con Python 3.10 y numpy<=1.26
